# example of creating a cluster via a ns scoped object
apiVersion: demo.anthos.com/v1
kind: Cluster
metadata:
  name: nanyu-gcp2
  labels:
    cluster-owner: nanyu
spec:
  compositionRef:
      # Possible values cluster-gcp-gke, cluster-aws-eks, cluster-azure-aks
    name: cluster-gcp-gke
  parameters:
    # Possible values small, medium, large
    nodeSize: medium
    k8sVersion: "1.24"
    fleetProject: "335365370934"
    minNodeCount: 2
    adminUsers:
    - nanyu@google.com
